schema_version = "1.0.0"

id = "bl_sisync"
version = "1.0.0"
name = "SiSync Maya - Blender"
tagline = "Round-trip mesh geometry and refresh shared PBR material maps between Autodesk Maya and Blender"
maintainer = "siddhartha adhikari"
type = "add-on"

tags = ["Pipeline", "Import-Export"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

